#!/bin/bash

echo "🚀 TaskPal Simple Startup Guide"
echo "==============================="
echo ""

echo "1. 🔧 Starting Backend..."
echo "   Run this in Terminal 1:"
echo "   cd backend"
echo "   export PATH=\"/opt/maven/bin:\$PATH\""
echo "   java -jar target/taskpal-backend-0.0.1-SNAPSHOT.jar"
echo ""

echo "2. 💻 Starting Frontend..."
echo "   Run this in Terminal 2:"
echo "   cd frontend"
echo "   export PATH=\"\$PATH:\$HOME/Documents/Master Software Engineering/SoftwareMethodologies/flutter/bin\""
echo "   flutter run -d chrome --web-port=3000"
echo ""

echo "3. 🌐 Open Browser:"
echo "   Frontend: http://localhost:3000"
echo "   Backend:  http://localhost:8080/api"
echo ""

echo "📝 Manual Steps:"
echo "================"
echo ""
echo "Terminal 1 (Backend):"
echo "cd backend"
echo "export PATH=\"/opt/maven/bin:\$PATH\""
echo "java -jar target/taskpal-backend-0.0.1-SNAPSHOT.jar"
echo ""
echo "Terminal 2 (Frontend):"
echo "cd frontend"
echo "export PATH=\"\$PATH:\$HOME/Documents/Master Software Engineering/SoftwareMethodologies/flutter/bin\""
echo "flutter run -d chrome --web-port=3000"
echo ""
echo "🎯 That's it! Your TaskPal app will be running!" 